### ISSUE TITLE
PDFKit font issues 

### ISSUE THREAD

**Issue by sarsena** [pdfkit/pdfkit#199]
Hi I have an Ubuntu server that im using to for a packing slip Rails app.  I using PDFKit to generate the pdf's.  The issue I am having is when I go to packing.slip.com/123456.pdf one of the two fonts I am using is not being rendered.   The HTML version does show up correctly I may add its just when rendering the .pdf version.

I am using MuseoSans 100 and MuseoSans 300 both as .ttf files.   Its really odd because sometimes either MuseoSans 100 renders for all text or MuseoSans 300 renders for all next but never together.

On my local development machine which is OS X both fonts show up and the pdf looks just like it does in the html version.

I have even changed the font name from MuseoSans to FontTest for the 300 version to see if that was an issue but still no dice.

Any advice would be greatly appreciated!

I have in my application.css.  

@font-face {
  font-family: 'FontTest';
  src: url('pdf/museosans_300-webkit.ttf') format('truetype');
  font-weight: 300;
  font-style: normal;
}

@font-face {
  font-family: 'MuseoSans';
  src: url('pdf/museosans_100-webkit.ttf') format('truetype');
  font-weight: 100;
  font-style: normal;
}

and I have used the base64 version too and still have no success

@font-face {
  font-family: 'FontTest';
  src: url(data:font/truetype;charset=utf-8;base64, [long-string]) format('truetype');
  font-weight: 300;
  font-style: normal;
}

@font-face {
  font-family: 'MuseoSans';
  src: url(data:font/truetype;charset=utf-8;base64, [long-string]) format('truetype');
  font-weight: 100;
  font-style: normal;
}

**Comment by sabliao** [comment]
@sarsena did you ever figure out the issue? I'm seeing something similar while running pdfkit with python on my Ubuntu virtual machine where my html shows Times New Roman in the places I specify to have different font but my pdf is almost completely Arial (except for the footer, whose font type is separately specified)

**Comment by sshishov** [comment]
Same issue here, different fonts are rendered only using one type at a time

**Comment by 91juhwang** [comment]
Same issue as well. Different fonts for font-face but using only 1 of them..

**Comment by bitterloa** [comment]
I'm not sure if this was the issue you guys were having but for me i couldn't get any fonts specified in my CSS to show up, and it turned out to be an issue with wkhtmltopdf and not necessarily with pdfkit. I think that wkhtmltopdf needs to have the font you specified installed *locally* so perhaps the font isn't available locally on the machine where it's not showing up. For me, I'm running Rails/PDFkit in a Docker container running Ubuntu, and needed to install fonts locally to Ubuntu.

Also, for some stupid reason I had to put quotes around a font that normally does not need this at all in css for wkhtmltopdf to 'see it', like this: `font-family: 'serif';` 

None of this is obvious and it's difficult to debug. I'm putting this here in case it might help someone else.

Please check this thread to see if it helps:
https://github.com/mileszs/wicked_pdf/issues/46
