### ISSUE TITLE
kit.to_file call never returns

### ISSUE THREAD

**Issue by thbar** [pdfkit/pdfkit#200]
The call to `to_file` seems to hang the execution on my setup.

Here is the code (I'm new to pdfkit so I may make an obvious mistake, but in case):

```ruby
task :default do
  require 'redcarpet'
  require 'pdfkit'

  content = IO.read('inventory.md')
  options = []
  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, *options)

  kit = PDFKit.new(markdown.render(content), :page_size => 'Letter')

  puts "Calling to_file"
  file = kit.to_file('inventory.pdf')
  puts "After to_file"
end
```

"After to_file" is never displayed (but the pdf is properly generated).

My configuration:

- ruby-1.9.3-p448 (with railsexpress patches, but I tried with 2.0.0 and see the same behaviour)
- pdfkit 0.5.4
- redcarpet 3.0.0

**Comment by zhangyanan** [comment]
I have the same issue on windows 7.
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
Exit with code 1 due to network error: HostNotFoundError

RuntimeError (command failed (exitstatus=1): C:/wkhtmltopdf/bin/wkhtmltopdf.exe --page-size Legal --print-media-type - -):
help me plz

**Comment by canercak** [comment]
+1

**Comment by cdwort** [comment]
@Alshurafa @zhangyanan Those look like real failures of the wkhtmltopdf command. PDFKit is erroring out with a message of `command failed (exitstatus=1):` Most likely that means either a problem with wkhtmltopdf or with your options set up. Those problems should go on StackOverflow first, but if you still think it's a bug feel free to open an issue.

The hanging problem, however, seems to be addressed by downgrading wkhtmltopdf or (most likely) using a newer version. I am closing this issue.
