### ISSUE TITLE
WeasyPrint implementation

### ISSUE THREAD

**Issue by cveneziani** [pdfkit/pdfkit#218]
That would be great to have a pdfkit implementation of WeasyPrint.

Are there other users of this engine?

http://weasyprint.org/
https://github.com/Kozea/WeasyPrint

**Comment by burningTyger** [comment]
Opening pdfkit up with an API would be great. Since wkhtmltopdf doesn't really work on ARM – neither does phantom.js – it would be great to have more options available. In this case slimer.js. There seems to be a Ruby wrapper for each of these renderers but they're all different and not easily replaced. One project to rule them all would be greatly appreciated and so far pdfkit does the best job :)
