### ISSUE TITLE
Result differs when rendering pdf or sending data

### ISSUE THREAD

**Issue by AdrienGiboire** [pdfkit/pdfkit#276]
I have the following codes:

```
  def show_pdf
    define_invoice
    define_informations
    
    render :pdf => pdf.to_pdf 
  end

  def save_pdf
    define_invoice
    define_informations

    filename = "Facture-" + @invoice.project.nom_struct + "-" + @invoice.id.to_s + ".pdf"
    send_data( pdf.to_pdf, :filename => filename, :type => 'application/pdf' )
  end

  def pdf
    @pdf = true
    html = render_to_string(:action => 'save_pdf', :layout => false)
    footer = @information.invoice_footer ? @information.invoice_footer : ""

    return PDFKit.new(html, :footer_right => footer , :margin_bottom => "30")
  end
```

the `save_pdf` method renders the pdf well but the `show_pdf` method renders the pdf without the footer.

I've debugged and in both case `footer` variable is well defined. the only difference is `send_data` versus `render :pdf`.

any idea?

**Comment by cdwort** [comment]
Hi @AdrienGiboire 

If one Rails method renders correctly but the other one doesn't, this does not seem to be an issue with PDFKit. This seems to be an issue with how ActionController::Rendering#render and ActionController::DataStreaming#send_data handle input.

Any chance this is an issue with encoding? I've seen issues with what kind of data #send_data expects. E.g.: http://stackoverflow.com/questions/23083983/send-pdf-with-rails-send-data.

Since this is a Rails problem, I am closing this issue.

**Comment by cdwort** [comment]
Hm, okay, that link suggests you would get an exception if the result of kit.to_pdf wasn't processable, so that's likely not the solution... There's still nothing I can see for PDFKit to do here.
