### ISSUE TITLE
Timeout dependencies

### ISSUE THREAD

**Issue by pkpp1233** [pdfkit/pdfkit#279]
Some of the HTML I want to convert to PDF has improper dependencies - as in an Image tag may have a src URL that doesn't exist anymore.

Is there a way to timeout loading dependencies when converting to HTML? If a dependency doesn't load in 10 seconds, forget it?

**Comment by serene** [comment]
What do you currently see? I would expect the image not to load. There is a timeout built into wkhtmltopdf. You can override the javascript-delay if you want to set a specific timeout.

**Comment by cdwort** [comment]
Hi @pkpp1233 

wkhtmltopdf currently offers no way to configure a timeout. It is a requested feature, however: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1888

PDFKit is just a wrapper around the wkhtmltopdf command-line. We allow for easy creation and execution of wkhtmltopdf commands, but we don't and can't really do much more.

For what it's worth, I do hope that wkhtmltopdf implements that feature! For now, though, since there's nothing this gem can do, I'm closing this issue. If wkhtmltopdf does implement a flag to configure timeouts, you should just be able to pass that flag to PDFKit, once you've upgraded wkhtmltopdf.

Thanks, 
Amy

**Comment by oshanz** [comment]
@cdwort wkthml doesn't seems working on that. what do you think about this pull request https://github.com/pdfkit/pdfkit/pull/368
