### ISSUE TITLE
PDFKit not applying the specified 'css' stylesheet.

### ISSUE THREAD

**Issue by prasadsurase** [pdfkit/pdfkit#288]
I have a html page displaying some images from Facebook CDN which needs to be converted to pdf as is. I am using ruby (2.2.0), rails (4.2.1), pdfkit(0.6.2) and have installed wkhtmltopdf(0.9.9) to the local box using 'sudo apt-get install'. 
  I precompiled the assets and copied the public/assets/application-xx.css to app/assets/stylesheets/pdf.css. Have replaced the asset urls in the css with absolute path (from /home/prasad/...). Have confirmed that all the referenced assets(fonts & images) are accessible by referring each them in browser url and making sure that they are downloadable.
  The problem is that the pdf is being generated but without the css being applied. The images from the CDN are being displayed.

```ruby
Started GET "/home/generate_pdf.pdf" for 127.0.0.1 at 2015-04-10 18:20:25 +0530
Processing by HomeController#generate_pdf as PDF
  Rendered home/generate_pdf.html.haml within layouts/application (9.2ms)
Loading page (1/2)
[============================================================] 100%
Printing pages (2/2)                                               
Done                                                           
  Rendered text template (0.0ms)
Sent data booklet.pdf (23.2ms)
Completed 200 OK in 61753ms (Views: 23.0ms)
```
  Have posted the same on Stackoverflow but couldn't find the solution hence have posted it here. https://github.com/prasadsurase/topdf.git is a sample repo reproducing the issue.

**Comment by cdwort** [comment]
Hi @prasadsurase ,

I was able to get the stylesheets to display fine for me. 
<img width="717" alt="screen shot 2015-08-19 at 8 01 09 pm" src="https://cloud.githubusercontent.com/assets/1014482/9373197/34476b70-46ad-11e5-8296-354b4c048de8.png">

I did notice a couple roadblocks with getting wkhtmltopdf to work with the application:

- A couple image links were broken
- wkhtmltopdf demands full links to CSS & JS, so I just commented out those lines in the layout/application.html.haml file. Since you are including the CSS in the controller, this doesn't matter for this particular issue.

I am closing this issue, but feel free to update with additional information and I will reopen.
