### ISSUE TITLE
Exec format error  issue in windows platform

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [pdfkit/pdfkit#306]
Hi,I am trying to converting html to pdf but got the following error.

Errno::ENOEXEC in UsersController#download_pdf

Exec format error - c:/Site/generate/bin/wkhtmltopdf-amd64 --encoding UTF-8 --page-size A4 --margin-top 0.25in --margin-right 0.1in --margin-bottom 0.25in --margin-left 0.1in --quiet - -

I have a setup like below and i want to run this application on windows 7(64 bit)/xp(32 bit).

PDFKit.configure do |config|

    #if your site is hosted on heroku or any other hosting server which is 64bit
    config.wkhtmltopdf = Rails.root.join('bin', 'wkhtmltopdf-amd64').to_s
 
  config.default_options = {
    :encoding=>"UTF-8",
    :page_size=>"A4",
    :margin_top=>"0.25in",
    :margin_right=>"0.1in",
    :margin_bottom=>"0.25in",
    :margin_left=>"0.1in",
    :disable_smart_shrinking=> false
  }
end
Please help me to resolve this type of issue.

**Comment by sigmavirus24** [comment]
I'm pretty sure this is one of a couple possible problems:

1. `C:/Site/generate/bin/` isn't a valid path (since you're using Rails to generate this though, I doubt this is the case)
2. `wkhtmltopdf-amd64` isn't an executable that Windows knows how to run
3. `C:/Site/generate/bin/wkhtmltopdf-amd64` isn't the full file name (e.g., might be `C:/Site/generate/bin/wkhtmltopdf-amd64.exe`

ENOEXEC is a very Google-able exception and very commonly (if not exclusively) seen on Windows. I don't have a windows machine to test this against though and I don't know where `wkhtmltopdf-amd64` comes from on your system. Perhaps you could research how other people have dealt with this problem.

Could you copy and paste the command that pdfkit tries to run into a command-line on Windows (powershell, cmd.exe, or whatever) and see if it gives you an error?

**Comment by cdwort** [comment]
I am closing this issue because we don't have enough information to investigate it. If you are able to provide the information above, please post it here and we'll re-open this issue. 

Thanks!
