### ISSUE TITLE
pdfkit success in development, failing in production with Passenger

### ISSUE THREAD

**Issue by castlese** [pdfkit/pdfkit#330]
I am successfully creating a pdf in development by running rails with unicorn and multiple workers. The same pdf is failing in staging environment which is running on Passenger 3 in Engineyard hosted server. 

It fails without an exitstatus:
RuntimeError: command failed (exitstatus=): /data/cashanalytics/shared/bin/wkhtmltopdf --page-size A3 --margin-top 0.3in --margin-right 0.3in --margin-bottom 0.3in --margin-left 0.3in --encoding UTF-8 --orientation Landscape - -

I have the wkhtmltopdf-binary gem in my bundle but it's also installed via a cookbook

**Comment by cdwort** [comment]
Hi @castlese 

This looks like PDFKit is generating the correct `wkhtmltopdf` command, but that there is an issue with `wkhtmltopdf` rendering your pdf.

Usually this is due to lack of access to an image or stylesheet that is referenced in your markup. 

Here are some things that might help you debug the issue:

Can you render the page as HTML without any assets missing? Are there any image links that are broken? If you open your developer panel and look at the network pane, are you including any stylesheets or JS files that 404 or 500?

**Comment by castlese** [comment]
Hi @cdwort, thanks for the speedy response. You were right in that the compiled javascript asset was not being loaded correctly. 

I'm still figuring out the fix. I am loading javascript to create a Google Visualization chart however, even though it works in the html version (no missing assets, no js errors - chart renders correctly), the same set up does not work in the pdf version. Is there any other way to troubleshoot javascript rendering in pdfkit?

**Comment by cdwort** [comment]
Hi castlese,

Well, it depends. In relatively rare cases we do see issues with PDFKit, so if you can post the code you're using to call PDFKit, from your controller or middleware, that could be helpful.

More likely though, your problem is not `troubleshoot javascript rendering in pdfkit` but rather how to troubleshoot whatever `wkhtmltopdf` is complaining about. 

What PDFKit gets you is the ability to build up the command you saw in your logs:

```
.../shared/bin/wkhtmltopdf --page-size A3 --margin-top 0.3in --margin-right 0.3in --margin-bottom 0.3in --margin-left 0.3in --encoding UTF-8 --orientation Landscape - -
```

The two dashes at the end mean that `wkthmltopdf` is looking for input from STDIN and outputting to STDOUT. So, it's possible that PDFKit is messing up the payload sent into STDIN.

Otherwise it's a wkhtmltopdf issue. 

If you can post information about your setup here, maybe we can see something. Otherwise, making sure that the wkhtmltopdf versions are the same, can you hit your production HTML page? Can you run this command against it:

```
.../shared/bin/wkhtmltopdf --page-size A3 --margin-top 0.3in --margin-right 0.3in --margin-bottom 0.3in --margin-left 0.3in --encoding UTF-8 --orientation Landscape http://your.awesome.site/page.html
```

**Comment by cdwort** [comment]
I would also encourage you to Google for "wkhtmltopdf javascript".

This answer that suggests absolute URLs is one that has been useful in the past: http://stackoverflow.com/questions/6949685/create-pdf-with-wkhtmltopdf-and-rendering-javascript

**Comment by castlese** [comment]
@cdwort thanks - I have encountered the absolute url solution and I'll try some of your suggested troubleshooting (&googling) and see what I come up with

**Comment by cdwort** [comment]
Alright, I'm going to close this issue since GitHub Issues are for bug reports and feature requests. If you continue to post here, I will see it and I'll try to help.

In the future, StackOverflow is the place for usage problems.

Good luck!
