### ISSUE TITLE
get the wrong Chinese font

### ISSUE THREAD

**Issue by duyuanchao** [pdfkit/pdfkit#341]
Hi,

I am converting this web page to PDF ,http://www.qingfan.com/my_passport/1432

The letter font suppose to be the 'msyh', but in the pdf I got the wrong font (Song).

Does anybody have met this before?

And here is my code

import pdfkit

options = {
    'page-size': 'Letter',
    'quiet': '',
    'orientation' : 'Landscape',
    'no-pdf-compression':'',
    }

pdfkit.from_url('http://www.qingfan.com/my_passport/1432', '/Users/Du/Desktop/out.pdf', options=options)

**Comment by sigmavirus24** [comment]
A few things:

1. Your code is Python but this project is written in Ruby
2. You're asking a question on a *defect* tracker. You should be asking it on a site for questions, e.g., stackoverflow.com
3. Because you're asking a question about an barely related (by name and purpose only) project, I'm closing this issue and locking the comments.
