### ISSUE TITLE
Feature Request: Print to single, variable length page

### ISSUE THREAD

**Issue by imvunoah** [pdfkit/pdfkit#348]
Here's a feature request: I just want to export a PDF at 11" x n", where n is just the end of the rendered HTML content.

**Comment by cdwort** [comment]
Hello @imvunoah 

PDFKit (and other like it such as WickedPDF) is a thin wrapper around the command-line utility `wkhtmltopdf`. That project has declined to implement this feature so far: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1627

Their recommendation is to use the utility `wkhtmltoimage` to get an image and then convert it to PDF.

I agree this would be a nice feature, but it is not within the scope of this project since the underlying utility has yet to implement it. I'm sorry to not have a happier answer here.
