### ISSUE TITLE
Stuck at loadingpages(1/5)

### ISSUE THREAD

**Issue by SuperCobain** [pdfkit/pdfkit#361]
Halo i just tried to use pdfkit and having some trouble to generate my html to pdf.
i am using osx, and have installed wkhtmltopdf-binary
also added
gem 'pdfkit'
gem 'unicorn'
gem "wkhtmltopdf-binary"..

whenever tried to convert my page it stuck on loadingpages(1/5).
and before this happen a terminal wkhtmltopdf_darwin_386 pop up..

**Comment by JElbourne** [comment]
Hello; Had a similar issue and I feel I understand the problem after getting things to work.

In my case the generating to PDF would hang and nothing would happen, this sounds similar to your issue.
I found that the issue was cause by the Rails asset pipeline and while using the typical application layout template which included the css and js assets, it would hang and nothing would happen. The solution would be to use a template / layout which does not link to any assets through the asset pipeline instead simply link to a particular file using it's full path.

This is for css, js, and images.

Because of this you must be careful when using the middleware with a Rails application, that is simply appending the ".pdf" to the end of a url.

Perhaps a fix for this issue would, for now, simply be a more clear explanation in the readme file about not using the Rails asset pipeline with PDFkit.
