### ISSUE TITLE
Hashes in URL get encoded

### ISSUE THREAD

**Issue by wutangpaul** [pdfkit/pdfkit#370]
I'm running an Angular client application where a typical URL look like this:  
`http://localhost:9000/#/document/view/12345`

When I pass that URL in to PDFKit like so:

`kit = PDFKit.new('http://localhost:9000/#/document/view/12345')`

 it attempts to dial out to the URL like this:

`2016-07-20 17:56:08 - RuntimeError - command failed (exitstatus=1): C:/wkhtmltopdf/bin/wkhtmltopdf.exe --javascript-delay 2000 "http://localhost:9000/%23/document/print/12345" C:/generated_pdfs/12345.pdf`

...which doesn't exist. Something is encoding the hash part of the url to %23.

Every other kind of URL I've tried works fine, it only craps out when the hash is introduced.

Any suggestions for a workaround? I can't change the URL structure of the Angular application, unfortunately.

**Comment by sigmavirus24** [comment]
I believe it happens [here](https://github.com/pdfkit/pdfkit/blob/master/lib/pdfkit/source.rb#L40) in spite of the comment [here](https://github.com/pdfkit/pdfkit/blob/master/lib/pdfkit/pdfkit.rb#L41..L43). I think we did that to ensure that a URL wasn't supplied that has `"`s in it which then allowed #164 to crop up again. I think we just need to delineate which characters we view to be [unsafe for the URI module](http://ruby-doc.org/stdlib-2.3.1/libdoc/uri/rdoc/URI/Escape.html#method-i-escape) rather than relying on its default. Make sense?
