### ISSUE TITLE
undefined method `protocol=' for #<PDFKit::Configuration

### ISSUE THREAD

**Issue by pirj** [pdfkit/pdfkit#385]
It seems that [README is misleading](https://github.com/pdfkit/pdfkit/commit/2febadcd028d51e73d8187745c54dabefd2597d2#diff-04c6e90faac2675aa89e2176d2eec7d8R79):

    config.protocol = 'http'

while this is not part of `Configuration`:

```ruby
class PDFKit
  class Configuration
    attr_accessor :meta_tag_prefix, :default_options, :root_url
```

and neither used by `Middleware`:

```ruby
    def translate_relative_protocols(body, env)
      protocol = "#{env['rack.url_scheme']}://"
```

Same applies to master.

Is there a good reason for this option to exist?

**Comment by pirj** [comment]
Besides working around `wkhtmltopdf`'s `Exit with code 1 due to network error: ProtocolUnknownError` issue.

**Comment by davidpatters0n** [comment]
@pirj  - Also having this problem. @danbernier would you know what may have changed?

**Comment by danbernier** [comment]
I'm not sure - it may have been an error on my part. I'm looking into the specs now.

**Comment by danbernier** [comment]
I took a closer look at the code, and I'm pretty sure I botched that README update - like @pirj pointed out, `protocol` isn't a configuration option. Hard to say for certain, since it was a while ago, and my memory is fuzzy, but that's how it looks. Apologies for that.

I'll submit a PR to fix the README. @pirj, I'd suggest you open an issue/submit a PR if you'd like the functionality added.

**Comment by davidpatters0n** [comment]
@danbernier  - Thanks.
