### ISSUE TITLE
URI.escape/unescape warnings

### ISSUE THREAD

**Issue by ethn** [pdfkit/pdfkit#492]
Not a major issue, just wanted to flag rather frequent warnings showing up in ruby 2.7.3:

~/.gem/ruby/2.7.3/gems/pdfkit-0.8.5/lib/pdfkit/source.rb:45: warning: URI.unescape is obsolete
~/.gem/ruby/2.7.3/gems/pdfkit-0.8.5/lib/pdfkit/source.rb:41: warning: URI.escape is obsolete

Thanks for pdfkit!

**Comment by ethn** [comment]
Perhaps more significant: these URI method calls (#escape, #unescape, #decode) prevent pdfkit from working in ruby 3. They have removed the methods after some ten years of deprecation.

**Comment by JensDebergh** [comment]
I don't have the time to whip up a merge request to get this issue fixed inside of the gem itself. I'm using this in the context of a rails application. The gist is the same for plain ruby.

For anyone stumbling on this issue here's the fix:

1) Add webrick to your Gemfile

```
gem "webrick"
```

2) Monkey patch the `Source` class

```
# config/initializers/pdfkit.rb
# Monkey patch for PDFKit ruby 3.0.0
require "webrick"
class PDFKit
  class Source
    private

      def shell_safe_url
        url_needs_escaping? ? WEBrick::HTTPUtils.escape(@source) : @source
      end

      def url_needs_escaping?
        WEBrick::HTTPUtils.unescape(@source) == @source
      end
  end
end
```
